import { mkdtemp, mkdir, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { beforeEach, describe, expect, it } from "vitest";
import {
  buildContext,
  camelOf,
  constOf,
  hostOf,
  hostPatternOf,
  pascalOf,
  sharedSchemaFromTests,
  slugOf,
  type ConsumerAuthContext,
} from "../src/web/consumer-auth/context.js";
import { parseTwoEnvFacts } from "../src/web/consumer-auth/facts.js";
import {
  addConsumerRules,
  checkConsumerAuth,
  ensureEmulatorsBlock,
  ensureTsExtensionImports,
  plannedFiles,
  rootScriptSet,
  scaffoldConsumerAuth,
  unitTestPath,
} from "../src/web/consumer-auth/scaffold.js";
import * as libs from "../src/web/consumer-auth/templates-lib.js";
import * as app from "../src/web/consumer-auth/templates-app.js";
import * as suites from "../src/web/consumer-auth/templates-tests.js";
import type { WebSurvey } from "../src/web/survey.js";

/**
 * The templates were extracted from Evo, where every property asserted below
 * was a review finding first (cpheinrich/morpheus#135). These tests pin the
 * extraction, not the application: Evo's own suites — which travel with the
 * scaffold — pin the behaviour.
 */

const ctx: ConsumerAuthContext = buildContext({
  name: "Acme",
  sharedPackageName: "@acme/shared",
  publicDomain: "acme.example",
  stagingDomain: "https://staging.acme.example",
  supportEmail: "support@acme.example",
  webRoot: "apps/web",
  production: {
    projectId: "ac-acme",
    apiKey: "prod-api-key",
    authDomain: "ac-acme.firebaseapp.com",
    storageBucket: "ac-acme.firebasestorage.app",
    messagingSenderId: "111111",
    appId: "1:111111:web:aaaa",
  },
  staging: {
    projectId: "ac-acme-staging",
    apiKey: "staging-api-key",
    authDomain: "ac-acme-staging.firebaseapp.com",
    storageBucket: "ac-acme-staging.firebasestorage.app",
    messagingSenderId: "222222",
    appId: "1:222222:web:bbbb",
  },
  workloadIdentity: {
    poolId: "vercel",
    providerId: "vercel-oidc",
    serviceAccount: "vercel-hq@ac-acme.iam.gserviceaccount.com",
  },
});

const survey: WebSurvey = {
  webRoot: "apps/web",
  webAppExists: true,
  alias: "@/",
  shared: {
    dir: "packages/shared",
    name: "@acme/shared",
    hasExportsMap: true,
    exportsWaitlist: true,
  },
  testRunner: "node",
  hasTailwind: true,
  hasWaitlist: true,
  hasHqRoute: true,
  hasSignIn: true,
  hasFirebaseConfig: true,
  hasRouteGate: true,
  firestoreRulesPath: "infra/firebase/firestore.rules",
  vercelLinked: true,
  staticExport: false,
  trailingSlash: true,
};

/** A minimal generated-shaped rules file: role helpers plus the catch-all. */
const RULES = `rules_version = '2';

service cloud.firestore {
  match /databases/{database}/documents {

    // morpheus:begin roles — generated by \`morpheus hq rules\`, do not edit
    function role() {
      return request.auth != null ? request.auth.token.get('role', '') : '';
    }
    // morpheus:end roles

    // Anything not named above is closed. Listed explicitly so that adding a
    // collection is a deliberate act rather than an inherited default.
    match /{document=**} {
      allow read, write: if false;
    }
  }
}
`;

async function fixture(): Promise<string> {
  const root = await mkdtemp(join(tmpdir(), "consumer-auth-"));
  await mkdir(join(root, "apps/web"), { recursive: true });
  await mkdir(join(root, "packages/shared"), { recursive: true });
  await mkdir(join(root, "infra/firebase"), { recursive: true });
  await writeFile(
    join(root, "package.json"),
    `${JSON.stringify({ name: "acme", private: true, scripts: {} }, null, 2)}\n`,
  );
  await writeFile(
    join(root, "apps/web/package.json"),
    `${JSON.stringify(
      { name: "@acme/web", scripts: { test: "node --test" }, dependencies: { next: "16.0.0" } },
      null,
      2,
    )}\n`,
  );
  await writeFile(
    join(root, "packages/shared/package.json"),
    `${JSON.stringify(
      { name: "@acme/shared", exports: { "./schema/waitlist": "./schema/waitlist.ts" } },
      null,
      2,
    )}\n`,
  );
  await writeFile(join(root, "infra/firebase/firestore.rules"), RULES);
  await writeFile(
    join(root, "firebase.json"),
    `${JSON.stringify({ firestore: { rules: "infra/firebase/firestore.rules" } }, null, 2)}\n`,
  );
  await writeFile(join(root, "pnpm-workspace.yaml"), "packages:\n  - apps/*\n  - packages/*\n");
  return root;
}

describe("context derivation", () => {
  it("derives every identifier form from one name", () => {
    expect(slugOf("Heinrich Money")).toBe("heinrich-money");
    expect(camelOf("Heinrich Money")).toBe("heinrichMoney");
    expect(pascalOf("Heinrich Money")).toBe("HeinrichMoney");
    expect(constOf("Heinrich Money")).toBe("HEINRICH_MONEY");
  });

  it("strips a scheme from a domain and keeps a bare host", () => {
    expect(hostOf("https://staging.acme.example")).toBe("staging.acme.example");
    expect(hostOf("acme.example")).toBe("acme.example");
  });

  it("escapes dots in the host pattern", () => {
    // Unescaped, `acme.example` also matches `acmexexample` — the lookalike
    // the known-host allowlist exists to refuse.
    expect(hostPatternOf("acme.example")).toBe("acme\\.example");
  });

  it("computes the schema path relative to the app's test directory", () => {
    expect(sharedSchemaFromTests("apps/web")).toBe("../../../packages/shared/schema/user.ts");
    expect(sharedSchemaFromTests(".")).toBe("../packages/shared/schema/user.ts");
  });
});

describe("template invariants", () => {
  it("keeps the emulator branch dead without the env var", () => {
    // The alg:none acceptance path must be keyed on FIREBASE_AUTH_EMULATOR_HOST
    // read at call time — an attacker-crafted unsigned cookie must never
    // authenticate against a real deployment.
    const rendered = libs.libAuthSessionCookie(ctx);
    expect(rendered).toContain("process.env.FIREBASE_AUTH_EMULATOR_HOST");
    expect(rendered).toContain("emulatorClaims");
  });

  it("anchors the known-host allowlist on both escaped hosts", () => {
    const rendered = libs.libAuthRequestOrigin(ctx);
    expect(rendered).toContain("acme\\.example");
    expect(rendered).toContain("staging\\.acme\\.example");
    expect(rendered).toContain("isKnownAcmeHost");
  });

  it("builds the reset route's constant answer per call, not at module scope", () => {
    // A module-level NextResponse body is a one-shot stream: first caller gets
    // {"ok":true}, everyone after an empty body — an enumeration oracle built
    // out of a caching mistake. Found on Evo by asking three times.
    const rendered = app.apiResetPasswordRoute(ctx);
    expect(rendered).toContain("function accepted()");
    expect(rendered).not.toMatch(/const accepted = NextResponse/);
  });

  it("mints the session only after the CSRF origin check", () => {
    const rendered = app.apiAuthSessionRoute(ctx);
    expect(rendered.indexOf("isSameOrigin")).toBeGreaterThan(-1);
    expect(rendered.indexOf("isSameOrigin")).toBeLessThan(rendered.indexOf("createSessionCookie"));
  });

  it("keeps the hint cookie readable and the session cookie httpOnly", () => {
    const rendered = app.apiAuthSessionRoute(ctx);
    expect(rendered).toContain("httpOnly: true");
    expect(rendered).toContain("httpOnly: false");
    // The name itself lives in the config, prefixed per project.
    expect(libs.libFirebaseConfig(ctx)).toContain('"acme_signed_in"');
  });

  it("checks deliverability before generating an action code", () => {
    // Generating revokes the outstanding code of the same type, so
    // generate-then-fail-to-send kills the link already in the inbox.
    const rendered = libs.libAuthSendActionEmail(ctx);
    expect(rendered.indexOf("canDeliver()")).toBeLessThan(
      rendered.indexOf("generateEmailVerificationLink"),
    );
  });

  it("points the E2E helper at the project the client bundle resolves", () => {
    // The exec project must match the bundle's (staging, since VERCEL_ENV is
    // absent at build time) or the Auth emulator splits one logical account
    // across two project ids.
    expect(suites.e2eEmulatorHelper(ctx)).toContain('PROJECT_ID = "ac-acme-staging"');
    expect(rootScriptSet(survey, ctx)["test:e2e"]).toContain("--project ac-acme-staging");
  });

  it("round-trips both environments through the config parser", () => {
    const facts = parseTwoEnvFacts(libs.libFirebaseConfig(ctx));
    expect(facts.production).toEqual(ctx.production);
    expect(facts.staging).toEqual(ctx.staging);
    expect(facts.workloadIdentity).toEqual(ctx.workloadIdentity);
  });
});

describe("scaffoldConsumerAuth", () => {
  let root: string;

  beforeEach(async () => {
    root = await fixture();
  });

  it("writes the plan, and a second run changes nothing", async () => {
    const first = await scaffoldConsumerAuth({ root, survey, ctx });
    expect(first.written.length).toBe(plannedFiles(survey, ctx).length);
    expect(first.drifted).toEqual([]);

    const second = await scaffoldConsumerAuth({ root, survey, ctx });
    expect(second.written).toEqual([]);
    expect(second.drifted).toEqual([]);
    expect(second.merged).toEqual([]);
  });

  it("never overwrites, and names a drifted plumbing file", async () => {
    const path = join(root, "apps/web/lib/auth/safe-next.ts");
    await mkdir(join(root, "apps/web/lib/auth"), { recursive: true });
    await writeFile(path, "// locally edited\n");

    const result = await scaffoldConsumerAuth({ root, survey, ctx });
    expect(result.drifted).toContain("apps/web/lib/auth/safe-next.ts");
    expect(await readFile(path, "utf8")).toBe("// locally edited\n");
  });

  it("inserts the consumer rules inside the service scope, above the catch-all", async () => {
    await scaffoldConsumerAuth({ root, survey, ctx });
    const rules = await readFile(join(root, "infra/firebase/firestore.rules"), "utf8");

    const users = rules.indexOf("match /users/{uid}");
    const catchAll = rules.indexOf("match /{document=**}");
    expect(users).toBeGreaterThan(-1);
    expect(users).toBeLessThan(catchAll);
    // Still exactly one catch-all, and the block landed before the closing
    // braces rather than after them.
    expect(rules.match(/match \/\{document=\*\*\}/g)).toHaveLength(1);
    expect(rules.trimEnd().endsWith("}")).toBe(true);

    // Idempotent: the presence check, not the anchor, decides on a re-run.
    const again = await addConsumerRules(root, "infra/firebase/firestore.rules");
    expect(again.kind).toBe("none");
  });

  it("refuses to write rules at a guessed position", async () => {
    await writeFile(
      join(root, "infra/firebase/firestore.rules"),
      "rules_version = '2';\nservice cloud.firestore {}\n",
    );
    const outcome = await addConsumerRules(root, "infra/firebase/firestore.rules");
    expect(outcome.kind).toBe("note");
  });

  it("merges the emulators block and leaves foreign ports alone", async () => {
    await scaffoldConsumerAuth({ root, survey, ctx });
    const parsed = JSON.parse(await readFile(join(root, "firebase.json"), "utf8")) as {
      emulators?: { auth?: { port?: number }; firestore?: { port?: number } };
    };
    // The rules suite dials these literally; a default that moved would make
    // it hang rather than fail.
    expect(parsed.emulators?.auth?.port).toBe(9099);
    expect(parsed.emulators?.firestore?.port).toBe(8080);

    await writeFile(
      join(root, "firebase.json"),
      JSON.stringify({ emulators: { auth: { port: 9199 }, firestore: { port: 8081 } } }),
    );
    const outcome = await ensureEmulatorsBlock(root, "infra/firebase/firestore.rules");
    expect(outcome.kind).toBe("note");
  });

  it("adds the missing emulators to a block that declares only the UI", async () => {
    // A ui-only block declares no conflicting port; refusing it as "different
    // ports" sends whoever reads the note hunting for a conflict that does
    // not exist.
    await writeFile(
      join(root, "firebase.json"),
      JSON.stringify({ emulators: { ui: { enabled: true, port: 4000 } } }),
    );
    const outcome = await ensureEmulatorsBlock(root, "infra/firebase/firestore.rules");
    expect(outcome.kind).toBe("merged");
    const parsed = JSON.parse(await readFile(join(root, "firebase.json"), "utf8")) as {
      emulators: { auth: { port: number }; firestore: { port: number }; ui: { port: number } };
    };
    expect(parsed.emulators.auth.port).toBe(9099);
    expect(parsed.emulators.firestore.port).toBe(8080);
    expect(parsed.emulators.ui.port).toBe(4000);
  });

  it("reports a foreign /users match instead of silently standing down", async () => {
    // A hand-written users rule means the collection is governed by rules this
    // scaffold has not seen — the one merge that must not no-op quietly.
    const rules = RULES.replace(
      "    // Anything not named above is closed.",
      "    match /users/{uid} {\n      allow read, write: if request.auth != null;\n    }\n\n    // Anything not named above is closed.",
    );
    await writeFile(join(root, "infra/firebase/firestore.rules"), rules);
    const outcome = await addConsumerRules(root, "infra/firebase/firestore.rules");
    expect(outcome.kind).toBe("note");
    // And nothing was written over the foreign rule.
    const after = await readFile(join(root, "infra/firebase/firestore.rules"), "utf8");
    expect(after).toBe(rules);
  });

  it("upgrades an unedited web-init config in place, and only that", async () => {
    const configPath = join(root, "apps/web/lib/firebase/config.ts");
    await mkdir(join(root, "apps/web/lib/firebase"), { recursive: true });
    await writeFile(configPath, "// what web init wrote\n");

    // Matching the recorded web-init render: upgraded to the two-env shape.
    const upgraded = await scaffoldConsumerAuth({
      root,
      survey,
      ctx,
      webInitConfig: "// what web init wrote\n",
    });
    expect(upgraded.upgraded).toContain("apps/web/lib/firebase/config.ts");
    expect(upgraded.drifted).not.toContain("apps/web/lib/firebase/config.ts");
    expect(await readFile(configPath, "utf8")).toContain("STAGING_CONFIG");
  });

  it("never upgrades a config that carries local edits", async () => {
    const configPath = join(root, "apps/web/lib/firebase/config.ts");
    await mkdir(join(root, "apps/web/lib/firebase"), { recursive: true });
    await writeFile(configPath, "// edited by a human\n");

    const result = await scaffoldConsumerAuth({
      root,
      survey,
      ctx,
      webInitConfig: "// what web init wrote\n",
    });
    expect(result.upgraded).toEqual([]);
    expect(result.drifted).toContain("apps/web/lib/firebase/config.ts");
    expect(await readFile(configPath, "utf8")).toBe("// edited by a human\n");
  });

  it("exempts the mail seam from drift, both in the run and in --check", async () => {
    // Swapping deliver()'s transport is the intended move while the provider
    // decision is open; the canonical choice must not read as drift.
    await scaffoldConsumerAuth({ root, survey, ctx });
    await writeFile(
      join(root, "apps/web/lib/email/send.ts"),
      "// a Cloudflare Email Sending deliver()\n",
    );
    const rerun = await scaffoldConsumerAuth({ root, survey, ctx });
    expect(rerun.drifted).toEqual([]);
    expect(await checkConsumerAuth({ root, survey, ctx })).toBe(0);
  });

  it("writes a .firebaserc with no default alias", async () => {
    // `firebase deploy` with no --project uses the default alias; leaving it
    // out means a stray deploy asks instead of silently picking production.
    await scaffoldConsumerAuth({ root, survey, ctx });
    const parsed = JSON.parse(await readFile(join(root, ".firebaserc"), "utf8")) as {
      projects: Record<string, string>;
    };
    expect(parsed.projects["default"]).toBeUndefined();
    expect(parsed.projects["prod"]).toBe("ac-acme");
    expect(parsed.projects["staging"]).toBe("ac-acme-staging");
  });

  it("merges root scripts and the shared export", async () => {
    await scaffoldConsumerAuth({ root, survey, ctx });

    const rootPkg = JSON.parse(await readFile(join(root, "package.json"), "utf8")) as {
      scripts: Record<string, string>;
      devDependencies: Record<string, string>;
    };
    expect(rootPkg.scripts["test:emulator"]).toContain("emulators:exec");
    expect(rootPkg.scripts["test:e2e"]).toContain("build:e2e");
    expect(rootPkg.devDependencies["@firebase/rules-unit-testing"]).toBeTruthy();

    const shared = JSON.parse(
      await readFile(join(root, "packages/shared/package.json"), "utf8"),
    ) as { exports: Record<string, string> };
    expect(shared.exports["./schema/user"]).toBe("./schema/user.ts");
  });

  it("check reports clean after a scaffold, and drift after an edit", async () => {
    await scaffoldConsumerAuth({ root, survey, ctx });
    expect(await checkConsumerAuth({ root, survey, ctx })).toBe(0);

    await writeFile(join(root, "apps/web/lib/auth/request-origin.ts"), "// edited\n");
    expect(await checkConsumerAuth({ root, survey, ctx })).toBe(1);
  });

  it("adds allowImportingTsExtensions to a plain-JSON tsconfig, and asks on JSONC", async () => {
    // The unit-testable modules import siblings by `./x.ts` path; without the
    // option, tsc refuses the specifiers (TS5097) and a fresh scaffold cannot
    // typecheck or build.
    await writeFile(
      join(root, "apps/web/tsconfig.json"),
      JSON.stringify({ compilerOptions: { noEmit: true } }),
    );
    expect((await ensureTsExtensionImports(root, "apps/web")).kind).toBe("merged");
    const parsed = JSON.parse(await readFile(join(root, "apps/web/tsconfig.json"), "utf8")) as {
      compilerOptions: Record<string, unknown>;
    };
    expect(parsed.compilerOptions["allowImportingTsExtensions"]).toBe(true);
    expect((await ensureTsExtensionImports(root, "apps/web")).kind).toBe("none");

    // Comments are legal in tsconfig.json and must not be rewritten away.
    await writeFile(
      join(root, "apps/web/tsconfig.json"),
      "{\n  // hand-tuned\n  \"compilerOptions\": { \"noEmit\": true }\n}\n",
    );
    expect((await ensureTsExtensionImports(root, "apps/web")).kind).toBe("note");
  });

  it("names the unit suites so they run, whatever the project's test runner", async () => {
    // `node --test` files nothing names run nowhere; on a vitest project the
    // default include would collect *.test.mjs and fail on node:test suites.
    expect(unitTestPath(survey, "auth-config")).toBe("__tests__/auth-config.test.mjs");
    expect(unitTestPath({ ...survey, testRunner: "vitest" }, "auth-config")).toBe(
      "__tests__/auth-config.node-test.mjs",
    );

    await scaffoldConsumerAuth({ root, survey, ctx });
    const appPkg = JSON.parse(await readFile(join(root, "apps/web/package.json"), "utf8")) as {
      scripts: Record<string, string>;
    };
    expect(appPkg.scripts["test:auth"]).toContain("__tests__/auth-config.test.mjs");
    // And the CI chain actually invokes it.
    expect(rootScriptSet(survey, ctx)["test:emulator:run"]).toContain("test:auth");
  });

  it("treats an emulator declared without a port as the default, not a conflict", async () => {
    // Firebase's defaults for auth and firestore are 9099 and 8080 — an
    // absent port already means the ports the suites dial.
    await writeFile(
      join(root, "firebase.json"),
      JSON.stringify({ emulators: { auth: { host: "127.0.0.1" }, firestore: { host: "127.0.0.1" } } }),
    );
    const outcome = await ensureEmulatorsBlock(root, "infra/firebase/firestore.rules");
    expect(outcome.kind).not.toBe("note");
  });

  it("check reads a missing rules configuration as drift, not as clean", async () => {
    await scaffoldConsumerAuth({ root, survey, ctx });
    const noRules = { ...survey, firestoreRulesPath: null };
    expect(await checkConsumerAuth({ root, survey: noRules, ctx })).toBe(1);
  });

  it("check covers the rules block, not only whole files", async () => {
    await scaffoldConsumerAuth({ root, survey, ctx });
    // Strip the consumer block back out: every whole file still matches, and
    // the one security-boundary merge is what must not pass unnoticed.
    await writeFile(join(root, "infra/firebase/firestore.rules"), RULES);
    expect(await checkConsumerAuth({ root, survey, ctx })).toBe(1);
  });
});
